import Head from 'next/head'


export default function Header ({}){
    const title: string="Laddre Tree";
    return( <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <meta property="og:title" content={title} />
            <meta property="og:type" content="video.movie" />
            <meta property="og:url" content="" />
            <meta property="og:image" content="" />
            </Head>
    )
}
